Bling/Models/PhotoStats.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProofOfConcept.Models
{
    public class PhotoStats
    {
        [Key]
        public int PhotoID { get; set; }

        public string LikedBy { get; set; }

        public string DisLikedBy { get; set; }

        public string LovedBy { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public DateTime DOU { get; set; }

        public int Likes
        {
            get { return LikedBy.Split(',').Count() - 2; }
        }

        public int Dislikes
        {
            get { return DisLikedBy.Split(',').Count() - 2; }
        }

        public int Loves
        {
            get { return LovedBy.Split(',').Count() - 2; }
        }
    }
}

Bling/Controllers/ContentController.cs
using ProofOfConcept.Models;
using ProofOfConcept.Services;
using System.Web;
using System.Web.Mvc;

namespace ProofOfConcept.Controllers
{
    public class ContentController : Controller
    {
        IUserDetailsService userDetails;
        public ContentController(IUserDetailsService userDetails)
        {
            this.userDetails = userDetails;
        }
        public ActionResult HomePage()
        {
            if (Session["UserID"] != null)
            {
                var user = userDetails.GetUser(Session["UserID"].ToString());
                if (user.ProfilePic != null)
                {
                    string[] path = user.ProfilePic.Split('/'); path[6] = "w_400,h_400,c_crop,g_face,r_max/w_200";
                    var newpath = string.Join("/", path);
                    Session["ProfilePic"] = newpath;
                }
                Session["Username"] = user.Username;
                string email = (string)TempData["Email"];
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult MyProfile()
        {
            bool loggedin = false;
            if (Session.Count > 0) {
                loggedin = (bool)Session["LoggedIn"];
            }
            
            if (Session["UserID"] != null)
            {
                var user = userDetails.GetUser(Session["UserID"].ToString());
                return View(user);
            }
            else
                return RedirectToAction("Index", "Home");

        }

        public ActionResult Edit(int id)
        {
            if (Session["UserID"] != null)
            {
                var user = userDetails.GetUser(Session["Email"].ToString());
                return View(user);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserDetails user)
        {
            if (Session["UserID"] != null)
            {
                if (ModelState.IsValid)
                {
                    var result = userDetails.EditUser(user);
                    return RedirectToAction("MyProfile");
                }
                else return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult ChangeProfilePic()
        {
            if (Session["UserID"] != null)
            {
                //return RedirectToAction("Picture","UploadPic",new { uploadType= "Change Profile Pic" }) ;
                ViewBag.UploadType = "Change Profile Pic";
                return View("UploadPic");
            }
            else return RedirectToAction("Index", "Home");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeProfilePic(HttpPostedFileBase picture) {
            if (Session["UserID"] != null)
            {
                if (picture.ContentLength > 0 && picture.ContentType.Contains("image"))
                {
                    bool result = userDetails.UploadPic(picture, Session["UserID"].ToString());
                    if (result == false)
                    {
                        ViewBag.Status = "Upload Failed!!!";
                        return View();
                    }
                }
                return RedirectToAction("MyProfile");
            }
            else return RedirectToAction("Index", "Home");
        }
    }
}

Bling/Controllers/PhotoStatsController.cs
using ProofOfConcept.Models;
using ProofOfConcept.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProofOfConcept.Controllers
{
    public class PhotoStatsController : Controller
    {
        IPhotoStatsService photoStatsService;
        public PhotoStatsController(IPhotoStatsService photoStatsService) {
            this.photoStatsService = photoStatsService;
        }
        [HttpPost]
        public string RecordStats(int id,char action)
        {
            string email = Session["Email"].ToString();
            PhotoStats photoStats = photoStatsService.RecordStats(email,id,action);
            if (photoStats != null)
            {
                Stats stats = new Stats() { Success=true, Loves = photoStats.Loves, Stat = "Nostats", Likes = photoStats.Likes, Dislikes = photoStats.Dislikes };
                if (photoStats.LikedBy.IndexOf("," + Session["UserID"] + ",") > -1)
                    stats.Stat = "L"; //ViewBag.my_Stat = "Liked";
                else if (photoStats.DisLikedBy.IndexOf("," + Session["UserID"] + ",") > -1)
                    stats.Stat = "D"; //ViewBag.my_Stat = "Disliked";
                else if (photoStats.LovedBy.IndexOf("," + Session["UserID"] + ",") > -1)
                    stats.Stat = "H";//ViewBag.my_Stat = "Loved";
                else
                    stats.Stat = "No Stat"; //ViewBag.my_stat = "No stat";
                return Newtonsoft.Json.JsonConvert.SerializeObject(stats);
            }
            else return Newtonsoft.Json.JsonConvert.SerializeObject(new Stats() { Success = false });
        }
    }
    public class Stats {
        public int Likes;
        public int Loves;
        public int Dislikes;
        public bool Success;
        public string Stat;
    }
}

Bling/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProofOfConcept.Models;
using ProofOfConcept.Services;

namespace ProofOfConcept.Controllers
{
    public class PhotosController : Controller
    {
        // GET: Photos
        IPhotoService photoService;
        public PhotosController(IPhotoService photoService) {
            this.photoService = photoService;
        }

        public ActionResult Upload()
        {
            ViewBag.UploadType = "Upload Pic";
            return View("UploadPic");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase file, string caption)
        {
            if(Session["LoggedIn"]!=null && (bool)Session["LoggedIn"] == true)
            {
                if (file != null && file.ContentLength > 0 && (file.ContentType.Contains("image") || file.ContentType.Contains("video")))
                {
                    bool result = photoService.UploadPic(file, Session["UserID"].ToString(), caption);
                    if (result != false) {
                        if (file.ContentType.Contains("video")) {
                            ViewBag.filepath = result;
                            return View("Thumnail");
                        }
                    }
                    else
                    {
                        ViewBag.Status = "Upload Failed!!!";
                        return View();
                    }
                }
                else {
                    //ModelState.AddModelError("PhotoPath", "Please select an image to upload");
                    ViewBag.Status = "Please select an image to upload";
                    ViewBag.UploadType = "Upload Pic";
                    return View("UploadPic");
                }
                return RedirectToAction("Uploads");
            }
            else return RedirectToAction("Index", "Home");
        }

        public ActionResult Uploads()
        {
            if (Session["UserID"] != null)
            {
                string userid = Session["UserID"].ToString();
                List<Photos> photos = photoService.GetUploads(userid);
                ViewBag.UserId = Session["UserID"].ToString();
                return View(photos);
            }
            else return RedirectToAction("Index", "Home");
        }

        public ActionResult DisplayPhoto(int photoId)
        {
            if (Session["UserID"] != null)
            {
                string userid = Session["UserID"].ToString(); 
                bool result = photoService.SetTrending(photoId);
                PhotoCommentCombined photo = photoService.GetPhotoAndComments(photoId);
                ViewBag.UserId = Session["UserID"].ToString();
                return View(photo);
            }
            else return RedirectToAction("Index", "Home");
        }
    }
}

Bling/Controllers/PopularsController.cs
using ProofOfConcept.Models;
using ProofOfConcept.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProofOfConcept.Controllers
{
    public class PopularsController : Controller
    {
        IPhotoService photoService;
        public PopularsController(IPhotoService photoService)
        {
            this.photoService = photoService;
        }
        // GET: Populars
        public ActionResult Popular()
        {
            if (Session["UserID"] != null)
            {
                List<Photos> photos = photoService.GetPhotos();
                ViewBag.UserId = Session["UserID"].ToString();
                return View(photos);
            }
            else return RedirectToAction("Index", "Home");
        }
    }
}

Bling/Controllers/PresentController.cs
using ProofOfConcept.Models;
using ProofOfConcept.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProofOfConcept.Controllers
{
    public class PresentController : Controller
    {
        // GET: Present
        IPresentService ps;
        public PresentController(IPresentService ps) { this.ps = ps; }
        public ActionResult Feature(int? number)
        {
            Random rnd = new Random();
            ViewBag.UserId = Session["UserID"].ToString();
            if (number == null)
                return View(ps.Featured().OrderBy(x => rnd.Next()).Take(number ?? 5));
            else
                return PartialView(ps.Featured().OrderBy(x => rnd.Next()).Take(number ?? 5));
        }

        public ActionResult Trending(int? number) {
            ViewBag.UserId = Session["UserID"].ToString();
            if (number != null) 
            return PartialView(ps.Trending().Take(number??5));
            else
            return View(ps.Trending().Take(5));
        }
        
        public ActionResult RecentUploads(int? offset) {
            ViewBag.UserId = Session["UserID"].ToString();
            return View(ps.RecentUploads(offset??null).Take(12));
        }

        public ActionResult SearchResults(string keyword) {
            if (keyword.IndexOf("#") > -1) {
                ViewBag.UserId = Session["UserID"].ToString();
                return View("Posts", ps.SearchPosts(keyword)); }
            else
                return View("Users", ps.SearchUsers(keyword));
        }

        //public ActionResult SearchResults(string keyword) {
        //    if (keyword.IndexOf('#') > -1)
        //        return View("Posts",ps.Search<Photos>(keyword));
        //    else
        //        return View("Users",ps.Search<UserDetails>(keyword));
        //}
    }
}

Bling/Controllers/UserController.cs
using ProfilerApp.Models;
using ProofOfConcept.Models;
using ProofOfConcept.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProofOfConcept.Controllers
{
    public class UserController : Controller
    {
        IUserService userService;
        public UserController(IUserService userService)
        {
            this.userService = userService;
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            int result = userService.AddUser(user);
            if (result!=0)
            {
                TempData["Email"] = user.Email;
                Session["LoggedIn"] = true;
                Session["Email"] = user.Email;
                Session["UserID"] = result;
                return RedirectToAction("HomePage","Content");
            }
            else
            {
                ViewBag.Success = "Attempt failed";
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login user)
        {
            UserAuth result = userService.AuthenticateUser(user);
            if (result.UserID > 0)
            {
                TempData["Email"] = user.Email;
                Session["LoggedIn"] = true;
                Session["Email"] = user.Email;
                Session["UserID"] = result.UserID;
                if (result.Role.Trim() == "Admin")
                    return RedirectToAction("Index", "Admin");
                else
                {
                    if (user.ReturnURL != null) return Redirect(user.ReturnURL);
                    else
                        return RedirectToAction("HomePage", "Content");
                }
            }
            else
            {
                ViewBag.Success = "Attempt failed";
            }
            return View();
        }

        public ActionResult Signout() {
            Session.Abandon();
            Session.RemoveAll();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ForgotPassword() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForgotPassword(string email) {
            if (userService.ForgotPassword(email))
                return View("MailSent");
            else
                ViewBag.Error="User not found";
                return View();
        }

        public ActionResult SetPassword(string guid, string email) {
            if (userService.MatchGuid(guid, email))
            {
                ViewBag.Email = email;
                return View();
            }
            return View("ForgotPassword");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetPassword(SetPassword passwordmodel) {
            userService.SetPassword(passwordmodel);
            return RedirectToAction("HomePage", "Content");
        }
        public ActionResult ChangePassword() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePassword changePassword) {
            if (ModelState.IsValid)
            {
                if (changePassword.NewPassword == changePassword.ConfirmPassword)
                {
                    if (userService.ChangePassword(changePassword, Session["UserID"].ToString()))
                    {
                        return RedirectToAction("HomePage", "Content");
                    }
                    else {
                        ViewBag.Status = "Attempt failed";
                    }
                }
            }
            return View();
        }
    }
}

Bling/Views/Shared/Contents.cshtml
@model IEnumerable<ProofOfConcept.Models.Photos>
<div class="picContainer row flex-row flex-nowrap">
    @foreach (var item in Model)
    {
        <div class="col-lg-4 col-md-3 col-sm-3 col-xs-6 text-center box" style="padding:15px;height:inherit" id="@item.PhotoID">
            <div class="imagecontainer thumbnail" id="@item.PhotoID">
                @Html.Partial("PhotoStat", item)
            </div>
        </div>
    }
</div>
<link href="~/Content/stats.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Scripts/UI.js"></script>
<script src="~/Scripts/Uploads.js"></script>

Bling/Views/Shared/PhotoStat.cshtml
@model ProofOfConcept.Models.Photos

@{if (Model.ContentType.Trim() == "Video")
    {
        <a href="@Url.Action("DisplayPhoto", "Photos",new { @photoId=Model.PhotoID})" class="thumbnail img-responsive text-center">
            <img src="@Model.PhotoPath" class="thumbnails" value="tyrytghfc" />
            <input type="hidden" value="@Model.Gif" />
        </a>
        @*<div class="thumbnail img-responsive text-center">
                <video controls style="width:100%">
                <source id='preview' src="@Model.PhotoPath">
                Video Preview
                </video>
            </div>*@
    }
    else
    {
        <a href="@Url.Action("DisplayPhoto", "Photos",new { @photoId=Model.PhotoID})" class="thumbnail img-responsive text-center">
            @{var path = Model.PhotoPath.Split('/'); path[6] = "w_300";}
            <img src="@string.Join("/", path)" class="thumbnails" value="tyrytghfc" />
        </a>
    }
}

<div id="stats">
    <span>@Html.DisplayFor(modelItem => Model.Loves)</span>
    @{ var UserId = ViewBag.UserId.ToString(); }
    <span class="glyphicon @((Model.LovedBy.IndexOf("," + UserId + ",") > -1)?"glyphicon-heart":"glyphicon-heart-empty") " style="color:hotpink"></span>
    |
    <span>@Html.DisplayFor(modelItem => Model.Likes)</span>
    <span class="glyphicon glyphicon-thumbs-up @((Model.LikedBy.IndexOf("," + UserId + ",") > -1)?"liked":"")"></span>
    |
    <span>@Html.DisplayFor(modelItem => Model.Dislikes)</span>
    <span class="glyphicon glyphicon-thumbs-down @((Model.DisLikedBy.IndexOf("," + UserId + ",") > -1)?"disliked":"")"></span>
</div>

Bling/Views/Shared/UploadPic.cshtml
<h4>Choose Picture</h4>
<hr />
<br />
@{  var ActionName = "";
    var ControllerName = "";
    var imageonly = "";
    if (ViewBag.UploadType == "Change Profile Pic")
    {
        ActionName = "ChangeProfilePic";
        ControllerName = "Content";
        imageonly = "image/*";
    }
    else if (ViewBag.UploadType == "Upload Pic")
    {
        ActionName = "Upload";
        ControllerName = "Photos";
        imageonly = null;
    }
}
@using (Html.BeginForm(ActionName, ControllerName, FormMethod.Post, new { encType = "multipart/form-data" }))
{
    <p style="color:red">@ViewBag.Status</p>
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @ViewBag.Status
            @Html.Label("Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ if (ViewBag.UploadType == "ChangeProfilePic")
                    {
                        @Html.TextBox("file", "", htmlAttributes: new { @class = "Required", type = "file", id = "picfield", accept = @imageonly })
                    }
                    else
                    { @Html.TextBox("file", "", htmlAttributes: new { @class = "Required", type = "file", id = "picfield" })
                }
                }
                @*@Html.TextBox("file", "", htmlAttributes: new { @class = "Required", type = "file", id = "picfield", accept = @imageonly })*@
            </div>
        </div>
            @{  if (ViewBag.UploadType == "Upload Pic")
                {
                    <div class="form-group">
                        @Html.Label("Caption", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextArea("caption","", htmlAttributes : new { @class = "form-control" } )
                        </div>
                    </div>
                }
             }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div class="previewdiv" style="display:none">
    <h6>Picture Preview</h6>
    <span id="previewfield"></span>
</div>

<script>
    $('#picfield').change(function () {
        if (this.files && this.files[0]) {
            if (this.files[0].type == "image/jpeg")
                $('#previewfield').html("<img src=" + $('#picfield').val() + " id='preview' alt='Picture Preview' width='200vh' / >");
            else if (this.files[0].type == "video/mp4")
                $('#previewfield').html("<video width='200vh' controls><source id='preview' src = " + $('#picfield').val() + "> Video Preview</video>");
            var reader = new FileReader();
            reader.onload = function (e) {
                debugger;
                $('.previewdiv').show();
                //.attr('src', e.target.result);
            }
            $('#preview')[0].src = URL.createObjectURL(this.files[0]);
            reader.readAsDataURL(this.files[0]);
        }
    });
</script>

Bling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <script src="~/Scripts/Layout.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" style="float:left !important;color:white" onclick="openNav()" >
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<span style="font-size:30px;cursor:pointer;float:left;color:white" onclick="openNav()">&#9776;</span>*@
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="padding:0 0 0 3px">
                    <span class="test"></span>                    
                </button>
                @Html.ActionLink("Profiler", "Home", "Content", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float:right">
                    <li>@Html.ActionLink("Settings","Settings","User")</li>
                    <li>@Html.ActionLink("Change Password", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sign Out", "SignOut", "User")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content col-lg-12 col-md-12 col-sm-12">
        <div id="mySidenav" class="sidenav col-lg-3 col-sm-3 col-md-3">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="name">
                @{var profilepic = Session["profilePic"] ?? "https://res.cloudinary.com/blinging/image/upload/w_200/defaultuser.png"; }
                <img src="@profilepic" class="profilepic" />
                <p class="">Hello, @Session["Username"]</p>
            </div>
            @Html.ActionLink("Home", "HomePage", "Content")
            @Html.ActionLink("My Profile", "MyProfile", "Content")
            @Html.ActionLink("Uploads", "Uploads", "Photos")
            @Html.ActionLink("Popular", "Popular", "Populars")
        </div>
        <div class="sidenavspace col-sm-4 col-md-3 col-lg-2 " style="height:100vh">
        </div>
        <div class="body col-md-8 col-lg-8 col-sm-8" style="padding:0 0 0s 50px">
            <div class="searchform">
                <form action="@Url.Action("SearchResults","Present")" method="get">
                    <input type="text" placeholder="Search" value="" name="keyword" style="max-width:80%"/>
                    <button type="submit" name="searchbtn" value=""><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
            <br />
            <div>
            @RenderBody()
            </div>
            <footer style="margin:0 10vh 0 10vh">
                <hr />
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </footer>
        </div>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bling/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
     
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div style="box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16), 0 2px 10px 0 rgba(0,0,0,0.12);background-color:white">
            <h1 style="margin: 0px 0 0 0;padding: 2% 0% 1% 5%;">
                Profiler
            </h1>
        </div>
        @*<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Profiler", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>*@
    </div>
    <div class="body-content" style="margin-top:3%">
        @RenderBody()
    </div>

    <footer style="margin:10vh">
        <hr />
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>